#!/usr/bin/env bash
# main-menu.sh — interactive launcher for common Squad admin actions.
#
# Runs as PID 1's foreground program inside the container (see entrypoint.sh).
# Intentionally ignores Ctrl+C and Ctrl+Z so the menu stays available.

set -euo pipefail

trap '' INT TSTP
stty -echoctl 2>/dev/null || true

cleanup() {
  stty echoctl 2>/dev/null || true
}
trap cleanup EXIT

pause() {
  echo ""
  read -r -p "Press Enter to return to menu... " _ </dev/tty || true
}

menu_clear() {
  # Avoid relying on `clear`/`tput` being installed.
  printf '\033[2J\033[H'
}

have_captain_tmux() {
  tmux has-session -t captain 2>/dev/null
}

show_web_ui_qr() {
  local url
  url=""
  if [[ -f /tmp/voice-url.txt ]]; then
    url="$(cat /tmp/voice-url.txt 2>/dev/null | tr -d '\r' | head -1 || true)"
  fi

  if [[ -z "${url}" ]]; then
    echo "ERROR: /tmp/voice-url.txt missing or empty; cannot display QR."
    return 1
  fi

  echo ""
  echo "Web UI URL:"
  echo "  ${url}"
  echo ""
  node /opt/squad/voice/show-qr.js "${url}"
}

run_interactive() {
  # Temporarily re-enable Ctrl+C/Ctrl+Z for interactive subprocesses.
  trap - INT TSTP
  stty echoctl 2>/dev/null || true

  set +e
  "$@"
  local rc=$?
  set -e

  trap '' INT TSTP
  stty -echoctl 2>/dev/null || true
  return "$rc"
}

restart_voice_server() {
  local voice_pid proc_env _oai _ant _tok _cap new_pid

  voice_pid="$(pgrep -f "node /opt/squad/voice/server.js" | head -1 || true)"

  if [[ -n "${voice_pid}" ]] && [[ -r "/proc/${voice_pid}/environ" ]]; then
    proc_env="$(tr '\0' '\n' <"/proc/${voice_pid}/environ" 2>/dev/null || true)"
    _oai="$(echo "${proc_env}" | sed -n 's/^OPENAI_API_KEY=//p' | head -1)"
    _ant="$(echo "${proc_env}" | sed -n 's/^ANTHROPIC_API_KEY=//p' | head -1)"
    _tok="$(echo "${proc_env}" | sed -n 's/^VOICE_TOKEN=//p' | head -1)"
    _cap="$(echo "${proc_env}" | sed -n 's/^SQUAD_CAPTAIN=//p' | head -1)"
  else
    # Best-effort fallbacks (entrypoint sources /home/ubuntu/env).
    _oai="${OPENAI_API_KEY:-${_OPENAI_API_KEY:-}}"
    _ant="${ANTHROPIC_API_KEY:-${_ANTHROPIC_API_KEY:-}}"
    _tok="${VOICE_TOKEN:-}"
    _cap="${SQUAD_CAPTAIN:-claude}"
  fi

  if [[ -z "${_oai}" ]]; then
    echo "ERROR: OPENAI_API_KEY not set; cannot start voice server."
    return 1
  fi
  if [[ -z "${_tok}" ]]; then
    echo "ERROR: VOICE_TOKEN not set; cannot start voice server."
    echo "Hint: it is generated by /opt/squad/launch-squad.sh at boot."
    return 1
  fi

  if [[ -n "${voice_pid}" ]]; then
    echo "Stopping voice server (PID ${voice_pid})..."
    kill "${voice_pid}" 2>/dev/null || true
    for _ in $(seq 1 10); do
      kill -0 "${voice_pid}" 2>/dev/null || break
      sleep 0.5
    done
    if kill -0 "${voice_pid}" 2>/dev/null; then
      echo "Force-killing voice server..."
      kill -9 "${voice_pid}" 2>/dev/null || true
      sleep 0.5
    fi
  else
    echo "No running voice server found; starting fresh."
  fi

  echo "Starting voice server..."
  OPENAI_API_KEY="${_oai}" \
  ANTHROPIC_API_KEY="${_ant}" \
  VOICE_TOKEN="${_tok}" \
  SQUAD_CAPTAIN="${_cap}" \
    node /opt/squad/voice/server.js > /tmp/voice-server.log 2>&1 &
  new_pid="$!"

  sleep 1
  if kill -0 "${new_pid}" 2>/dev/null; then
    echo "Voice server running (PID ${new_pid})."
  else
    echo "ERROR: voice server failed to start. Tail of /tmp/voice-server.log:"
    tail -20 /tmp/voice-server.log 2>/dev/null || true
    return 1
  fi
}

restart_pane_monitor() {
  echo "Restarting pane monitor..."
  pkill -f "/opt/squad/pane-monitor.sh" 2>/dev/null || true
  sleep 0.5

  if ! have_captain_tmux; then
    echo "ERROR: tmux session 'captain' not found."
    return 1
  fi

  if ! tmux list-windows -t captain -F '#{window_name}' 2>/dev/null | grep -q '^idle-monitor$'; then
    tmux new-window -t captain -n idle-monitor
  fi

  tmux send-keys -t captain:idle-monitor "/opt/squad/pane-monitor.sh 2>&1 | tee -a /tmp/pane-monitor.log" Enter
  sleep 0.5

  if pgrep -f "/opt/squad/pane-monitor.sh" >/dev/null 2>&1; then
    echo "Pane monitor running."
  else
    echo "WARNING: pane monitor did not start; check /tmp/pane-monitor.log"
    return 1
  fi
}

run_update_script_if_present() {
  local candidates=()
  shopt -s nullglob
  candidates+=(/home/ubuntu/*/utils/update.sh)
  candidates+=(/home/ubuntu/utils/update.sh)
  shopt -u nullglob

  for c in "${candidates[@]}"; do
    if [[ -x "${c}" ]]; then
      echo "Running ${c} ..."
      run_interactive "${c}"
      return $?
    fi
  done

  echo "No update script found under /home/ubuntu."
  echo "If you have this repo cloned in the container volume, run ./utils/update.sh from that clone."
  return 1
}

status_line() {
  local voice_url voice_pid cloud_pid cap="?"
  voice_url=""
  [[ -f /tmp/voice-url.txt ]] && voice_url="$(cat /tmp/voice-url.txt 2>/dev/null || true)"
  voice_pid="$(pgrep -f "node /opt/squad/voice/server.js" | head -1 || true)"
  cloud_pid="$(pgrep -f "cloudflared tunnel --url http://localhost:3000" | head -1 || true)"
  [[ -n "${SQUAD_CAPTAIN:-}" ]] && cap="${SQUAD_CAPTAIN}"

  echo "Captain: ${cap} | tmux: $(have_captain_tmux && echo up || echo down) | voice: ${voice_pid:-down} | tunnel: ${cloud_pid:-down}"
  [[ -n "${voice_url}" ]] && echo "Voice URL: ${voice_url}"
}

# Non-interactive entrypoint for tests/scripts.
if [[ "${1:-}" == "--action" ]]; then
  action="${2:-}"
  case "${action}" in
    status)
      status_line
      ;;
    show-web-ui)
      show_web_ui_qr
      ;;
    restart-idle-monitor)
      restart_pane_monitor
      ;;
    *)
      echo "Usage: $0 --action {status|show-web-ui|restart-idle-monitor}" >&2
      exit 2
      ;;
  esac
  exit $?
fi

while true; do
  menu_clear
  echo "Squad Main Menu"
  echo "==============="
  status_line
  echo ""
  echo "1) Connect to Captain (tmux attach)"
  echo "2) Restart Captain (claude)"
  echo "3) Restart Captain (codex)"
  echo "4) Restart Web UI (voice server)"
  echo "5) Restart Idle Monitor (pane-monitor)"
  echo "6) Launch Shell"
  echo "7) Run update script (if present in /home/ubuntu)"
  echo "8) Show Web UI QR code + URL"
  echo "q) Quit (exit container process)"
  echo ""

  read -r -p "Select> " choice </dev/tty || choice="q"

  case "${choice}" in
    1)
      if have_captain_tmux; then
        run_interactive tmux attach -t captain || true
      else
        echo "tmux session 'captain' not found yet."
        pause
      fi
      ;;
    2)
      if have_captain_tmux; then
        run_interactive /opt/squad/restart-captain.sh claude || true
      else
        echo "ERROR: tmux session 'captain' not found."
      fi
      pause
      ;;
    3)
      if have_captain_tmux; then
        run_interactive /opt/squad/restart-captain.sh codex || true
      else
        echo "ERROR: tmux session 'captain' not found."
      fi
      pause
      ;;
    4)
      restart_voice_server || true
      pause
      ;;
    5)
      restart_pane_monitor || true
      pause
      ;;
    6)
      run_interactive bash -l || true
      ;;
    7)
      run_update_script_if_present || true
      pause
      ;;
    8)
      show_web_ui_qr || true
      pause
      ;;
    q|Q)
      exit 0
      ;;
    *)
      echo "Unknown selection: ${choice}"
      pause
      ;;
  esac
done
